name: [GCF Deploy] Google Scholar

on:
  push:
    branches: [ main ]
    paths: 
      - data_sources/google_scholar/

  workflow_dispatch:

jobs:
  Deploy Function:
    name: Deploy Function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: ${{ secrets.GCF_ServiceAccount_Key }}
          name: GoogleScholar
          region: europe-west1
          source_dir: data_sources/google_scholar/
          entry_point: GoogleScholar
          memory_mb: 512MB
          runtime: python38
