name: Google Cloud Functions Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  DeployToGoogleScholar:
    name: Deploy To GoogleScholar
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          # Optional service account key to use for authentication to GCP. This should be the JSON formatted private key which can be exported from the Cloud Console. The value can be raw or base64-encoded.
          credentials: ${{ secrets.GCF_ServiceAccount_Key }}
          name: GitHubActionsTest
          description: Web Scraper handling the scraping of search results from Google Scholar for the ReSearch Engine
          region: europe-west1
          # Path to function deployment directory within the source repo.
          source_dir: GitHubActionsTest/test/
          entry_point: GitHubActionsTest
          memory_mb: 512MB
          runtime: python38
          service_account_email: mailforpranav247@gmail.com
          # Specifies which action should trigger the function.
#           event_trigger_type: # optional
          # Specifies which resource from eventTrigger is observed.
#           event_trigger_resource: # optional
          # The hostname of the service that should be observed.
#           event_trigger_service: # optional
