name: GCF Deploy - Microsoft Academic

on:
#   push:
#     branches: [ main ]
#     paths: 
#       - data_sources/google_scholar/**

  workflow_dispatch:

jobs:
  Deploy Function:
    name: Deploy Function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: ${{ secrets.GCF_ServiceAccount_Key }}
          name: MicrosoftAcademic
          region: europe-west1
          source_dir: data_sources/microsoft_academic/
          entry_point: MicrosoftAcademic
          memory_mb: 512MB
          runtime: nodejs14
